global:
  ingressSubdomain: mooc-cpat-ocp01-cluster.us-south.containers.appdomain.cloud
  tlsSecretName: mooc-cpat-ocp01-cluster

inventory-management-svc-lr:
  replicaCount: 3
  
  ingress:
    enabled: true
    tlsSecretName: mooc-cpat-ocp01-cluster

